name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            unzip \
            openjdk-11-jdk \
            zlib1g-dev \
            libncurses5-dev \
            libbz2-dev \
            liblzma-dev \
            libffi-dev \
            libsqlite3-dev \
            libssl-dev \
            libreadline-dev \
            libgdbm-dev \
            libnss3-dev \
            libgdbm-compat-dev \
            tk-dev \
            python3-pip \
            python3-venv \
            libtool \
            libjpeg-dev \
            libtiff-dev \
            automake \
            autoconf \
            pkg-config

      - name: Create virtual environment
        run: python3 -m venv venv

      - name: Install Cython and Virtualenv Dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install cython

      - name: Install Buildozer and Requirements
        run: |
          source venv/bin/activate
          python -m pip install buildozer
          python -m pip install -r requirements.txt

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: ~/.buildozer
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache Buildozer directory
        uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        run: |
          source venv/bin/activate
          buildozer android clean
          buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin/*.apk
